app/models.py
# -*- coding: UTF-8 -*-

from app import db
from flask_login import UserMixin
from datetime import datetime


class TodoList(db.Model):
    __tablename__ = 'todolist'
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, nullable=False)
    title = db.Column(db.String(1024), nullable=False)
    status = db.Column(db.Integer, nullable=False)
    create_time = db.Column(db.DateTime, nullable=False, default=datetime.now)

    def __init__(self, user_id, title, status):
        self.user_id = user_id
        self.title = title
        self.status = status


class User(UserMixin, db.Model):
    __tablename__ = "user"
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(100), nullable=False)
    password = db.Column(db.String(100), nullable=False)

    def __init__(self, username, password):
        self.username = username
        self.password = password

    def check_password(self, password):
        from werkzeug.security import check_password_hash
        return check_password_hash(self.password, password)

# if __name__ == '__main__':
#     db.create_all()
#     print("ok")

app/web/forms.py
# -*- coding: UTF-8 -*-
from __future__ import unicode_literals
from flask_wtf import FlaskForm
from wtforms import RadioField, SubmitField, StringField, PasswordField
from wtforms.validators import DataRequired, Length, ValidationError, EqualTo
from app.models import User


class TodoListForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired(), Length(1, 64)])
    status = RadioField('Done or Not Done', validators=[DataRequired()], choices=[("1", 'YES'), ("0", 'NO')])
    submit = SubmitField('submit')


class LoginForm(FlaskForm):
    username = StringField('username', validators=[DataRequired(), Length(1, 24)])
    password = PasswordField('password', validators=[DataRequired(), Length(1, 24)])
    submit = SubmitField('Login')

    def validate_username(self, field):
        username = field.data
        count = User.query.filter_by(username=username).count()
        if count == 0:
            raise ValidationError("account doesn't exist")


class RegisterForm(FlaskForm):
    username = StringField('username', validators=[DataRequired(), Length(1, 24)])
    password = PasswordField('password', validators=[DataRequired(), Length(1, 24)])
    confirm_password = PasswordField(
        label="confirm password",
        validators=[
            DataRequired(),
            EqualTo("password", message="Password and Confirm Password inconsistent"),
            Length(1, 24)
        ]
    )
    submit = SubmitField('Register')

    def validate_username(self, field):
        username = field.data
        count = User.query.filter_by(username=username).count()
        if count == 1:
            raise ValidationError("username is already taken")

app/__init__.py
# -*- coding: UTF-8 -*-
from __future__ import unicode_literals

from flask import Flask
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

app = Flask(__name__)
app.config.from_object('app.setting')
bootstrap = Bootstrap(app)

app.secret_key = app.config["SECRET_KEY"]
app.config['SQLALCHEMY_DATABASE_URI'] = app.config["MYSQL_DB_URL"]
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = True

db = SQLAlchemy(app)
login_manager = LoginManager(app)
login_manager.login_view = "web.login"

from app.web import web

app.register_blueprint(web)

app/web/__init__.py
# -*- coding:utf-8 _*-  
""" 
@author: ronething 
@file: __init__.py.py 
@time: 2019/01/09
@github: github.com/ronething 

Less is more.
"""

from flask import Blueprint

web = Blueprint("web", __name__)

# views 不能放在 web blueprint 前面 否则会报错
import app.web.views

app/web/views.py
# -*- coding:utf-8 _*-  
""" 
@author: ronething 
@file: views.py 
@time: 2019/01/09
@github: github.com/ronething 

Less is more.
"""

from flask import render_template, redirect, url_for, request, flash
from flask_login import login_required, login_user, logout_user, current_user
from app.web.forms import TodoListForm, LoginForm, RegisterForm
from app.models import TodoList, User
from app import db, login_manager
from werkzeug.security import generate_password_hash
from . import web


@web.route('/', methods=['GET', 'POST'])
@login_required
def show_todo_list():
    form = TodoListForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            todolist = TodoList(current_user.id, form.title.data, form.status.data)
            db.session.add(todolist)
            db.session.commit()
            flash('You have add a new todo list', 'success')
            return redirect(url_for('web.show_todo_list'))
        else:
            flash(form.errors)
    todolists = TodoList.query.filter_by(user_id=current_user.id).all()
    return render_template('index.html', todolists=todolists, form=form)


@web.route('/delete/<int:id>/')
@login_required
def delete_todo_list(id):
    todolist = TodoList.query.filter_by(id=id).first_or_404()
    db.session.delete(todolist)
    db.session.commit()
    flash('You have delete a todo list', 'info')
    return redirect(url_for('web.show_todo_list'))


@web.route('/change/<int:id>/', methods=['GET', 'POST'])
@login_required
def change_todo_list(id):
    form = TodoListForm()
    todolist = TodoList.query.filter_by(id=id).first_or_404()
    if request.method == 'POST':
        if form.validate_on_submit():
            todolist = TodoList.query.filter_by(id=id).first_or_404()
            todolist.title = form.title.data
            todolist.status = form.status.data
            db.session.commit()
            flash('You have modify a todolist', 'info')
            return redirect(url_for('web.show_todo_list'))
        else:
            flash(form.errors)
    form.title.data = todolist.title
    form.status.data = str(todolist.status)
    return render_template('modify.html', form=form)


@web.route('/register/', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        user = User(
            username=form.username.data,
            password=generate_password_hash(form.password.data)
        )
        db.session.add(user)
        db.session.commit()
        flash("register success and please login", "success")
        return redirect(url_for('web.login'))
    return render_template('register.html', form=form)


@web.route('/login/', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        user = User.query.filter_by(username=username).first()
        if user.check_password(password):
            login_user(user)
            flash('you have logged in!', 'info')
            return redirect(url_for('web.show_todo_list'))
        else:
            flash('Invalid username or password', 'danger')
    return render_template('login.html', form=form)


@web.route('/logout/')
@login_required
def logout():
    logout_user()
    flash('you have logout!', 'info')
    return redirect(url_for('web.login'))


@login_manager.user_loader
def load_user(user_id):
    return User.query.filter_by(id=int(user_id)).first()

app/templates/base.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/utils.html" as utils %}

{% block title %}TODO List{% endblock %}

{% block navbar %}
    <nav class="navbar navbar-inverse container">
        <div class="navbar-header"><a class="navbar-brand" href="{{ url_for('web.show_todo_list') }}">TODO</a></div>
        <!-- logout links -->
        {% if current_user.is_authenticated %}
            <ul class="nav navbar-nav pull-right">
                <li><a class="btn" href="{{ url_for('web.logout') }}">logout</a></li>
            </ul>
        {% endif %}
    </nav>
{% endblock %}

{% block content %}
    <div class="container">
        <!-- flash message -->
        {% with messages = get_flashed_messages(with_categories=True) %}
            {% if messages %}
                {{ utils.flashed_messages(messages,dismissible=True) }}
            {% endif %}
        {% endwith %}
        <!-- body block -->
        {% block page_content %} {% endblock %}
    </div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}

    <table class="table table-hover">
        <thead>
        <th class="active">No</th>
        <th class="active">描述</th>
        <th class="active">是否完成</th>
        <th class="active">创建时间</th>
        <th class='active'>操作</th>
        </thead>
        <tbody>
        {% for todo in todolists %}

            <!-- tr -->
            {% if todo.status %}
                <tr class="success">
                    {% else %}
                <tr class="info">
            {% endif %}
        <td>{{ loop.index }}</td>
        <td>{{ todo.title }}</td>
        <td>{{ todo.status }}</td>
        <td>{{ todo.create_time }}</td>
        <td>
            <a href="{{ url_for('web.delete_todo_list', id=todo.id) }}" class="btn btn-danger" role="button">删除</a>
            <a href="{{ url_for('web.change_todo_list', id=todo.id) }}" class="btn btn-success" role="button">修改</a>
        </td>
        </tr>
        {% endfor %}

        </tbody>
    </table>

    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal"> ADD</button>

    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">

                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span
                            aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title" id="myModalLabel" align="center">add new todo list</h4>
                </div>

                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-8 col-md-offset-2"> {{ wtf.quick_form(form) }} </div>
                    </div>
                </div> <!-- modal body -->

            </div>
        </div>
    </div>


{% endblock %}

app/templates/login.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <h2 class="form-signin-heading">Log In</h2>
            {{ wtf.quick_form(form) }}
        </div>
    </div>
    <div class="row">
        <a href="{{ url_for('web.register') }}"><p style="text-align: center">Don't have an account? Sign Up</p></a>
    </div>
{% endblock %}

app/templates/modify.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}

<div class="row">
    <h4 class="modal-title" id="myModalLabel" align="center"></h4>
    <div class="col-md-8 col-md-offset-2"> {{ wtf.quick_form(form) }} </div>
</div>

{% endblock %}

app/templates/register.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <h2 class="form-signin-heading">Sign Up</h2>
        {{ wtf.quick_form(form) }}
    </div>
</div>
{% endblock %}